import { Inter } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/header";

import { Providers } from "@/components/NextUiProviders";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Xem điểm trực tuyến",
    description: "Generated by create next app",
    icons: {
        icon: [
            {
                url: "/favicon_32x32.png", // /public path
                href: "/favicon_32x32.png", // /public path
            },
        ],
    },
};
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} box-border overflow-y-scroll`}>
                <Header />
                <Providers>
                    <main className="pt-[96px] bg-white min-h-screen ">{children}</main>
                </Providers>
            </body>
        </html>
    );
}
